version: 0.0
os: linux
files:
  - source: /
    destination: /app/clientTemp
permissions:
  - object: /app/client
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: deploy/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/afterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: root
